# Generated by Django 4.1.7 on 2023-04-01 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Bank Account Name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='other', max_length=7)),
                ('amount', models.CharField(max_length=6)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=18)),
                ('description', models.TextField(max_length=300)),
                ('category', models.ManyToManyField(blank=True, to='finances.category')),
                ('paid_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.bankaccount')),
            ],
        ),
    ]
