# Generated by Django 4.1.7 on 2023-04-01 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spending',
            name='category',
        ),
        migrations.AddField(
            model_name='spending',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.category'),
        ),
    ]
