# Generated by Django 4.1.7 on 2023-04-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_spending_category_spending_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
