# Generated by Django 4.1.7 on 2023-04-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_spending_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
