# Generated by Django 4.1.7 on 2023-05-07 17:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_alter_spending_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='spending',
            name='description',
            field=models.TextField(blank=True, max_length=300, validators=[django.core.validators.RegexValidator('[+-/%@!()"{}]', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='spending',
            name='location',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('[+-/%@!(){}]', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='spending',
            name='paid_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.bankaccount', verbose_name='Card'),
        ),
    ]
